#!/usr/bin/env python3

import hashlib
import os
import re
import sys
import urllib.request

FORMULA_FILE = "pyxel.rb"


def get_sha256(url):
    filename = os.path.basename(url)
    urllib.request.urlretrieve(url, filename)
    with open(filename, "rb") as file:
        sha256 = hashlib.sha256(file.read()).hexdigest()
    os.remove(filename)
    return sha256


def update_formula():
    if len(sys.argv) < 2:
        print("update_version VERSION")
        exit(1)

    version = sys.argv[1]
    release_url = f"https://github.com/kitao/pyxel/releases/download/v{version}/"
    macos_file = f"pyxel-{version}-macos.zip"
    linux_file = f"pyxel-{version}-linux.zip"
    macos_url = release_url + macos_file
    linux_url = release_url + linux_file
    macos_sha256 = get_sha256(macos_url)
    linux_sha256 = get_sha256(linux_url)

    with open(FORMULA_FILE, "r") as f:
        formula = f.read()
    formula = re.sub('url ".*"', f'url_ "{macos_url}"', formula, 1)
    formula = re.sub('url ".*"', f'url_ "{linux_url}"', formula, 1)
    formula = re.sub("url_", "url", formula)
    formula = re.sub('sha256 ".*"', f'sha256_ "{macos_sha256}"', formula, 1)
    formula = re.sub('sha256 ".*"', f'sha256_ "{linux_sha256}"', formula, 1)
    formula = re.sub("sha256_", "sha256", formula)
    with open(FORMULA_FILE, "w") as f:
        f.write(formula)


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    update_formula()
